use_default_settings: true

server:
  secret_key: "ghost-secret-key"
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: true
  base_url: "https://g-jxlf.onrender.com"

search:
  formats:
    - html
    - json
